apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
 containers:
   - name: simple-webapp-color
     image: simple-webapp-color
     ports:
       - containerPort: 8080
     # CONFIG MAP EXAMPLE use config-map.yaml
     envFrom:
       - secretRef:
             name: app-secret
     # SINGLE ENV EXAMPLE
     env:
       - name: DB_Password
         valueFrom:
           configMapKeyRef:
             name: app-secret
             key: DB_Password
     # VOLUME EXAMPLE
     volumes:
       - name:
         secret:
           secretName: app-secret