# https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
# https://kubernetes.io/docs/tasks/run-application/configure-pdb/
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: zookeeper
